// export.js
// Builds a plain-text summary report from window.AnalysisResults
// (populated by seoChecks.js, geoChecks.js, wordCount.js on every render)
// and lets the user copy it to clipboard or download it as a .txt file.

(function () {
  "use strict";

  const STATUS_PREFIX = { good: "[GOOD] ", ok: "[CHECK]", bad: "[FIX]  " };
  const SCORE_LABEL = { good: "Good", ok: "Needs work", bad: "Poor" };

  function buildReport() {
    const state = window.AppState.get();
    const results = window.AnalysisResults || {};
    const lines = [];

    lines.push("CONTENT ANALYSIS REPORT");
    lines.push("Generated: " + new Date().toLocaleString());
    lines.push("=".repeat(50));
    lines.push("");

    lines.push("Focus keyword: " + (state.focusKeyword || "(none set)"));
    lines.push("SEO title: " + (state.seoTitle || "(none set)"));
    lines.push("Meta description: " + (state.metaDesc || "(none set)"));
    lines.push("URL slug: " + (state.urlSlug || "(none set)"));
    lines.push("");

    if (results.wordcount) {
      const wc = results.wordcount;
      lines.push("-- WORD COUNT --");
      lines.push(`Words: ${wc.words}  |  Sentences: ${wc.sentences}  |  Paragraphs: ${wc.paragraphs}`);
      lines.push(`Characters (with spaces): ${wc.charsWithSpaces}  |  (no spaces): ${wc.charsNoSpaces}`);
      lines.push(`Avg words/sentence: ${wc.avgWordsPerSentence}  |  Reading time: ${wc.readingTime}  |  Speaking time: ${wc.speakingTime}`);
      if (wc.density.length) {
        lines.push("Top repeated phrases: " + wc.density.map((d) => `${d.phrase} (${d.count}x, ${d.density}%)`).join(", "));
      }
      lines.push("");
    }

    if (results.seo) {
      lines.push(`-- TRADITIONAL SEO -- Score: ${SCORE_LABEL[results.seo.score]} (${results.seo.percentage}%)`);
      results.seo.checks.forEach((c) => lines.push(`${STATUS_PREFIX[c.status]} ${c.text}`));
      lines.push("");
    }

    if (results.geo) {
      lines.push(`-- AI SEO / GEO -- Score: ${SCORE_LABEL[results.geo.score]} (${results.geo.percentage}%)`);
      results.geo.checks.forEach((c) => lines.push(`${STATUS_PREFIX[c.status]} ${c.text}`));
      lines.push("");
    }

    lines.push("=".repeat(50));
    lines.push("Generated by Content Analyzer (free, open-source, no backend).");

    return lines.join("\n");
  }

  function copyReport() {
    const text = buildReport();
    navigator.clipboard
      .writeText(text)
      .then(() => flashStatus("copyReportBtn", "Copied!"))
      .catch(() => {
        // Fallback for browsers without clipboard API permission
        const textarea = document.createElement("textarea");
        textarea.value = text;
        document.body.appendChild(textarea);
        textarea.select();
        try {
          document.execCommand("copy");
          flashStatus("copyReportBtn", "Copied!");
        } catch (e) {
          flashStatus("copyReportBtn", "Copy failed");
        }
        document.body.removeChild(textarea);
      });
  }

  function downloadReport() {
    const text = buildReport();
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "content-analysis-report.txt";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    flashStatus("downloadReportBtn", "Downloaded!");
  }

  function flashStatus(btnId, message) {
    const btn = document.getElementById(btnId);
    const original = btn.textContent;
    btn.textContent = message;
    setTimeout(() => (btn.textContent = original), 1500);
  }

  document.getElementById("copyReportBtn").addEventListener("click", copyReport);
  document.getElementById("downloadReportBtn").addEventListener("click", downloadReport);
})();
